version: '1.0'

services:
  welisten_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "45432:5432"
    networks:
      - shared_welisten
    volumes:
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  welisten_api:
    ports:
      - "10000:8080"
    networks:
      - shared_welisten
    env_file:
      - env.api

  welisten_seq:
    environment:
      - ACCEPT_EULA=Y
    networks:
      - shared_welisten
    ports:
      - "5341:5341"
      - "8081:80"

  welisten_client:
    ports:
      - "10001:8082"
    networks:
      - shared_welisten

networks:
  shared_welisten:
    name: welisten
    driver: bridge